name: Deploy MkDocs

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.25"
          python-version: "3.12"
          activate-environment: true

      - name: Install dependencies
        run: |
          uv sync

      - name: Download ISOFIT dependencies
        run: |
          isofit --base .. --path examples .           # Set the checked out repo as the examples path
          isofit download examples --neon --image_cube # Download only the needed additional datasets
          isofit download all --exclude examples       # Download all other ISOFIT extras
          isofit build

      - name: Build and deploy docs
        run: |
          VERSION=$(isofit --version)
          mike deploy --push --update-aliases "$(isofit --version)" latest
          mike set-default --push latest

  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.25"
          python-version: "3.12"
          activate-environment: true

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Download ISOFIT dependencies
        run: |
          isofit --base .. --path examples .           # Set the checked out repo as the examples path
          isofit download examples --neon --image_cube # Download only the needed additional datasets
          isofit download all --exclude examples       # Download all other ISOFIT extras
          isofit build

      - name: Build and deploy docs
        run: |
          mike deploy --push dev
